### ISSUE TITLE
Jairo's improvements

### ISSUE THREAD

**Issue by jczanfona** [Artem3213212/cuda_terminal#11]
This plugin is really useful!! It allows me many file operations using the [warpper](https://github.com/Alexey-T/CudaText/issues/2484#issuecomment-619188595)

Could it be possible to **close** the terminal when typing 'exit'?
And get **focus** when invoked?

TX a lot.

**Comment by Jairo-Martinez** [comment]
Hi @jczanfona 
If you are not working with your own requirement I can do it, I am ask to not to do duplicated work.

**Comment by jczanfona** [comment]
Of course, you can do it. I'm not working on it.
Dale duro!!!

**Comment by Jairo-Martinez** [comment]
Hi @jczanfona 

Could you validate what is done until now? credits from @kvichans:
Use this URL: "https://github.com/Jairo-Martinez/cuda_terminal.git"
![Snipaste_2020-05-06_21-20-20](https://user-images.githubusercontent.com/5806694/81247479-b972aa00-8fdf-11ea-80e5-f14031d69885.png)

Major changes:
- Change the Terminal settings to use the current "plugin settings" utility.
- Set focus on activate bottom panel.
- The icon for bottom panel is added when Cud starts.

Pending a change with look and feel.

*Larga vida a la Madre Patria*

**Comment by jczanfona** [comment]
Upsss, the URL seems to be wrong...

![image](https://user-images.githubusercontent.com/46503049/81272480-d645c680-904d-11ea-8dd1-6bbb0ea4629e.png)
And when Retry...
![image](https://user-images.githubusercontent.com/46503049/81272597-f5445880-904d-11ea-83b7-7a32a53fabb3.png)

**Comment by kvichans** [comment]
@Jairo-Martinez 
Why did you write
`https://github.com/Jairo-Martinez/cuda_terminal.git` ?
I see your plugin at 
`https://github.com/Jairo-Martinez/cuda_terminal`

**Comment by jczanfona** [comment]
That's true, @kvichans is right. TX

I think the focus now works very well 🎯
Now you can go ahead to the 'exit' part 🔨
Well done!

**Comment by jczanfona** [comment]
Why does `dir / w` behave differently (number of columns) in DOS compared to plugin?

**Comment by Jairo-Martinez** [comment]
> 
> 
> @Jairo-Martinez
> Why did you write
> `https://github.com/Jairo-Martinez/cuda_terminal.git` ?
> I see your plugin at
> `https://github.com/Jairo-Martinez/cuda_terminal`

My bad @kvichans thanks.

**Comment by Jairo-Martinez** [comment]
> 
> 
> Why does `dir / w` behave differently (number of columns) in DOS compared to plugin?

Quick response, I think that the Python sub-process is not enable to determine if there are control character that means a line return. Let me validate that.

**Comment by jczanfona** [comment]
Perhaps the same problem that typing `cal` in CT terminal with linux?

**Comment by Alexey-T** [comment]
@Jairo-Martinez can you pls

- move `import cuda_options_editor as op_ed` below, into code which calls Config dialog? this speeds up plugin loading.

**Comment by Alexey-T** [comment]
@Jairo-Martinez 
I dont get idea why you removed `timer_proc(TIMER_START, self.timer_update, 200, tag='')`
and all calls of `elf.Cmd.block.acquire()`

can you rename your python module to cuda_terminal_j so we will have your fork as different plugin? and publish it as 2nd "Terminal J" plugin

**Comment by Alexey-T** [comment]
you added on_start in install.inf. to show sidebar button on start? better do this w/o using on_start. see how plugin cuda_snippet_panel does it via install.inf.

**Comment by Alexey-T** [comment]
@Jairo-Martinez see #12 #13

**Comment by Jairo-Martinez** [comment]
@jczanfona please validate the "exit" part.

@Alexey-T I did what you wrote me about the fork. Help me to validate if is enough please. Thanks.

**Comment by Jairo-Martinez** [comment]
@jczanfona the link https://github.com/Jairo-Martinez/cuda_terminal_j

**Comment by Alexey-T** [comment]
@Jairo-Martinez installed your fork. at 1st look it works okay. "exit" works. combobox with dropdown appeared. 
I use Ubuntu.
i will test more.

**Comment by Alexey-T** [comment]
pls, open the "Issues" at repo of Terminal J. i will post more issues.

**Comment by Jairo-Martinez** [comment]
> 
> 
> pls, open the "Issues" at repo of Terminal J. i will post more issues.

Open! late but open now!

**Comment by Alexey-T** [comment]
moving discussion to Issues at https://github.com/Jairo-Martinez/cuda_terminal_j
