### ISSUE TITLE
fork's faster import

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/cuda_terminal#13]
@Jairo-Martinez can you pls     move 
`import cuda_options_editor as op_ed`
 below, into code which calls Config dialog? this speeds up plugin loading.

**Comment by Jairo-Martinez** [comment]
Excellent @Alexey-T I'll take a look what you mention.

**Comment by Jairo-Martinez** [comment]
Done

**Comment by Alexey-T** [comment]
no commit in your repo?

**Comment by Jairo-Martinez** [comment]
Nou no yet I am testing your other suggestion.
