### ISSUE TITLE
terminal_j: copy this patch

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/cuda_terminal#21]
https://github.com/Artem3213212/cuda_terminal/commit/2097ce428a04304dfa1573083b106b19837f13e7

@Jairo-Martinez

**Comment by Jairo-Martinez** [comment]
Have you the link of Cud v 1.99.1?

**Comment by Alexey-T** [comment]
it's not published.

**Comment by Alexey-T** [comment]
@Jairo-Martinez reminder about your fork.
