### ISSUE TITLE
Takes too much memory

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/cuda_terminal#22]
>Очень интересно оно память кушает, поставил плагин терминал в нем, запустил в терминале редактора скрипт на питоне на обработку Эксель файла в 4000 строк, так оно скушало 7Гб из 8 оперативы и зависло. Запускаем скрипт из терминала, ну 100мб кушает, в терминале vscode тоже 100-150.
sol13 ★★★★ (03.07.20 06:52:32)

**Comment by Artem3213212** [comment]
а там часом твой скрипт в консоль ничего не выдаёт?

**Comment by Alexey-T** [comment]
видимо выдает, потому и буфер забивается.

**Comment by Alexey-T** [comment]
Стоит сделать опцию "history_size"=1000, и убирать из буфера старые строки по ней

**Comment by Artem3213212** [comment]
мне сейчас совсем не до этого можешь сам по править?

**Comment by Alexey-T** [comment]
Хорошо

**Comment by Alexey-T** [comment]
сделал. дал опцию max_buffer_size. обновляю.
