### ISSUE TITLE
Cannot stop CudaText

### ISSUE THREAD

**Issue by kvichans** [Artem3213212/cuda_terminal#28]
После запуска Терминала не удается полностью закрыть Куд - подпроцесс не завершается.
ОС: Win10
shell_windows=cmd.exe

**Comment by Alexey-T** [comment]
делал правки. проверьте как сейчас. из гх.

**Comment by Alexey-T** [comment]
Thread не стопился. fixed. пробуем из гх.

**Comment by kvichans** [comment]
Да, теперь Куд закрывается до конца
