### ISSUE TITLE
Floating_window option

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/cuda_terminal#29]
@kvichans сделал. пробуем из гх. опция пишется в конфиг при откр.по  options/settings-plugins.

**Comment by kvichans** [comment]
Попробовал из ГХ с адресом
`https://github.com/Artem3213212/cuda_terminal`
получил
![image](https://user-images.githubusercontent.com/7419630/88918851-d6cbb300-d272-11ea-92fd-119cc5f9c159.png)

**Comment by Alexey-T** [comment]
он содержит. странно. сбои в МС

**Comment by kvichans** [comment]
Сейчас выдает
![image](https://user-images.githubusercontent.com/7419630/88954638-5c675700-d2a3-11ea-9e1f-86639c5a2261.png)

**Comment by kvichans** [comment]
Сейчас выдает
![image](https://user-images.githubusercontent.com/7419630/88954794-933d6d00-d2a3-11ea-97eb-45ef38f06d92.png)

**Comment by Alexey-T** [comment]
не знаю...

**Comment by kvichans** [comment]
(Скачал zip, обновил руками)
Плавающий Терминал работает. Но этим невозможно пользоваться без свойства "быть над всеми окнами Куд", так как у меня один экран.

**Comment by Alexey-T** [comment]
break- проблема есть. возился вчера весь день с переделкой плага. даже голова заболела. я хочу перевести его на либу pyte . и потом там будет с цветом (в юникс) и линус-шел будет ведеть ширину окна. и все такое.
 break в этой ветке править не хочу
новая ветка недоделана.

https://github.com/CudaText-addons/cuda_terminal
