### ISSUE TITLE
2 floating windows

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/cuda_terminal#30]
>Нажал в плавающем Терминале Break, вызвал Терминал из Куд, получил два плавающих окна

**Comment by Alexey-T** [comment]
делал правки сегодня. это не повтррил. проверьте их гх. теперь еще шелл автопускается после break.

**Comment by Alexey-T** [comment]
@kvichans ?

**Comment by kvichans** [comment]
Да, ДВА теперь не получить.
Но и ОДИН теперь не закрыть!

**Comment by kvichans** [comment]
Ни крест в титуле, ни Break правее ком.строки не закрывают

**Comment by Alexey-T** [comment]
сделал. пробуем из гх.
