### ISSUE TITLE
Terminal starts and hides behind Cud 

### ISSUE THREAD

**Issue by kvichans** [Artem3213212/cuda_terminal#31]
Терминал запускается в плавающем режиме и тут же прячется за Куд. Если Куд развернут на весь **единственный** экран, то НЕТ способа увидеть терминал.

**Comment by Alexey-T** [comment]
- при клике sidebar btn - так -но тут и не поправить, Куд забирает фокус
- при plugins/terminal- all ok

**Comment by kvichans** [comment]
Как это не поправить?! Заказать событие через таймер и вернуть фокус на форму - а?

**Comment by Alexey-T** [comment]
сделал. пробуем гх.

**Comment by kvichans** [comment]
Нда - не то :(
При любой передаче фокуса на Куд - Терм прячется навсегда.
Нужен именно флаг окна "поверх"

**Comment by Alexey-T** [comment]
Todo- опция

**Comment by Alexey-T** [comment]
сделал опцию. пробуем гх.

**Comment by kvichans** [comment]
Удалил файл настроек. Попросил новые. Не вижу что задать
```
[op]
shell_windows=cmd.exe
shell_unix=bash
shell_macos=bash
add_prompt_unix=1
dark_colors=0
floating_window=1
max_history=10
font_size=9
max_buffer_size=100000
encoding_windows=cp866
```

**Comment by Alexey-T** [comment]
у меня оно пишет -- опцию floating_window_topmost

**Comment by kvichans** [comment]
Видимо где-то оставался процесс.
Все позакрывал и удалил cuda_terminal.ini - теперь вижу новую опцию при заказе.

Стало норм.
