### ISSUE TITLE
PgUp/PgDn

### ISSUE THREAD

**Issue by kvichans** [Artem3213212/cuda_terminal#32]
Работают только стрелки. Это не серьезно. Без PgUp/PgDn жить нельзя

**Comment by kvichans** [comment]
Если сначала нажать Tab, то можно попасть внутрь "выдачи". Там работают PgUp/PgDn.
НО! обратно не удается вернуться

**Comment by Alexey-T** [comment]
Todo

**Comment by Alexey-T** [comment]
сделал. в гх.
