### ISSUE TITLE
macOS issues

### ISSUE THREAD

**Issue by tatecapone** [Artem3213212/cuda_terminal#8]
In Mac does not recognize the Node commands, among others ... And to make it work you have to launch it, then close it from the button and start it again so that it starts working...thanks.

**Comment by Alexey-T** [comment]
@Artem3213212 don't have a Mac. i have, will test it after a 1-2 months, so wait.

**Comment by Alexey-T** [comment]
Can you write what is "does not recognize the Node commands, among others "?
what do you enter in terminal plugin?

**Comment by tatecapone** [comment]
for example, node app.js, responds, node command not found ... also, when you open the terminal window the first time, do not let write anything, you have to restart the plugin to make it work.

**Comment by Alexey-T** [comment]
Currently no fix, so maybe Terminal plugin is not usable on Mac, sorry

**Comment by tatecapone** [comment]
No problem...isn't so necessary. Thanks!

**Comment by Alexey-T** [comment]
now I tested it on macOS 10.8. all is working.
yes, plugin panel shows as empty, its ok. just focus with mouse the lowest input (near the button Break). and type there "ls" [Enter]. first command "ls" runs ok.

first command "/usr/local/bin/node ~/a.js" runs ok. it shows errors in a.js.
@Artem3213212

**Comment by Alexey-T** [comment]
seems plugin needs to add PATH values. https://stackoverflow.com/questions/34984870/order-of-usr-bin-and-usr-local-bin-and-more-in-path
so "node" cannot run yet, after adding to PATH "node" will run.
todo.

**Comment by Alexey-T** [comment]
info too- https://sth.fyi/2016/10/01/really-really-add-usrlocalbin-to-the-path-variable-on-mac-os-x/

**Comment by Alexey-T** [comment]
done; path is changed on macos. pls is updated.

**Comment by tatecapone** [comment]
Alexey, I have tested it in the new version of cuda (1.86) and it works
perfectly ... very grateful! Thank you

**Comment by tatecapone** [comment]
Alexey...The cudatext update 1.86.5 is not for mac?
thxs!

**Comment by Alexey-T** [comment]
Mac version will be later

**Comment by tatecapone** [comment]
Ok...Thanks!
